//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Models.Standard.DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductFeatures = new HashSet<ProductFeature>();
        }

        [DataMember]
        public System.Guid UID { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string Description { get; set; }
        [DataMember]
        public string Version { get; set; }
        [DataMember]
        public string Code { get; set; }
        [DataMember]
        public string LegalCode { get; set; }
        [DataMember]
        public Nullable<int> ProductYear { get; set; }
        [DataMember]
        public string Category { get; set; }
        [DataMember]
        public string Manufacturer { get; set; }
        [DataMember]
        public string Unit { get; set; }
        [DataMember]
        public string Color { get; set; }
        [DataMember]
        public Nullable<bool> Service { get; set; }
        [DataMember]
        public string Picture { get; set; }
        [DataMember]
        public byte[] RowVersion { get; set; }
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductFeature> ProductFeatures { get; set; }
    }
}
