//
// This file was generated by the Jeddict
//
package controls.navs.content;

import java.io.Serializable;

public class LocaleItemKey implements Serializable {

    private String itemKey;

    private String itemLocale;

    public LocaleItemKey() {
    }

    public LocaleItemKey(String itemKey, String itemLocale) {
        this.itemKey = itemKey;
        this.itemLocale = itemLocale;
    }

    public String getItemKey() {
        return this.itemKey;
    }

    public void setItemKey(String itemKey) {
        this.itemKey = itemKey;
    }

    public String getItemLocale() {
        return this.itemLocale;
    }

    public void setItemLocale(String itemLocale) {
        this.itemLocale = itemLocale;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final LocaleItemKey other = (LocaleItemKey) obj;
        if (!java.util.Objects.equals(this.getItemKey(), other.getItemKey())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getItemLocale(), other.getItemLocale())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 11 * hash + (this.getItemKey() != null ? this.getItemKey().hashCode() : 0);
        hash = 11 * hash + (this.getItemLocale() != null ? this.getItemLocale().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "LocaleItemKey{" + " itemKey=" + itemKey + ", itemLocale=" + itemLocale + '}';
    }

}