/**
 * This file was generated by the Jeddict
 */
package controls.navs.content;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

@Entity
@Table(name = "locale_item")
@IdClass(LocaleItemKey.class)
public class LocaleItem implements Serializable {

    @Column(name = "item_key", table = "locale_item", nullable = false, length = 100)
    @Id
    protected String itemKey;

    @Column(name = "item_locale", table = "locale_item", nullable = false, length = 100)
    @Id
    protected String itemLocale;

    @Column(name = "item_value", table = "locale_item", nullable = false, length = 100)
    @Basic
    protected String itemValue;

    public String getItemKey() {
        return this.itemKey;
    }

    public void setItemKey(String itemKey) {
        this.itemKey = itemKey;
    }

    public String getItemLocale() {
        return this.itemLocale;
    }

    public void setItemLocale(String itemLocale) {
        this.itemLocale = itemLocale;
    }

    public String getItemValue() {
        return this.itemValue;
    }

    public void setItemValue(String itemValue) {
        this.itemValue = itemValue;
    }
}