/**
 * This file was generated by the Jeddict
 */
package controls.navs.content;

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.Serializable;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

@Entity
@Table(name = "navigation")
public class Navigation implements Serializable {

    @Column(name = "nav_id", table = "navigation")
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    protected Long id;

    @Column(name = "text_", table = "navigation", nullable = false, length = 100)
    @Basic(optional = false)
    protected String text;

    @Column(name = "locale_text", table = "navigation", length = 100)
    @Basic
    protected String localeText;

    @Column(name = "title", table = "navigation", length = 100)
    @Basic
    protected String title;

    @Column(name = "locale_title", table = "navigation", length = 100)
    @Basic
    protected String localeTitle;

    @Column(name = "css_class", table = "navigation", length = 100)
    @Basic
    protected String cssClass;

    @Column(name = "styles", table = "navigation", length = 100)
    @Basic
    protected String styles;

    @Column(name = "link_url", table = "navigation")
    @Basic
    protected String linkUrl;

    @Column(name = "link_title", table = "navigation", length = 100)
    @Basic
    protected String linkTitle;

    @Column(name = "link_locale_title", table = "navigation", length = 100)
    @Basic
    protected String linkLocaleTitle;

    @Column(name = "link_css_class", table = "navigation", length = 100)
    @Basic
    protected String linkCssClass;

    @Column(name = "link_styles", table = "navigation", length = 100)
    @Basic
    protected String linkStyles;

    @Column(name = "roles", table = "navigation", length = 100)
    @Basic
    protected String roles;

    @Column(name = "users", table = "navigation", length = 100)
    @Basic
    protected String users;

    @Column(name = "sort_order", table = "navigation")
    @Basic
    protected Integer sortOrder;

    @Column(name = "auth_mode", table = "navigation")
    @Basic
    protected Boolean authMode;

    @Column(name = "separator_", table = "navigation")
    @Basic
    protected Boolean separator;

    @Column(name = "navigation_menu_id")
    @Basic
    protected Long navigationMenuId;

    @Column(name = "parent_id")
    @Basic
    protected Long parentId;

    @ManyToOne(targetEntity = NavigationMenu.class)
    @JoinColumn(name = "nav_menu_id", referencedColumnName = "menu_id")
    @JsonIgnore
    protected NavigationMenu menu;

    @ManyToOne(targetEntity = Navigation.class)
    @JoinColumn(name = "nav_nav_id", referencedColumnName = "nav_id")
    @JsonIgnore
    protected Navigation parentItem;

    @OneToMany(cascade = {CascadeType.ALL}, fetch = FetchType.EAGER, targetEntity = Navigation.class, orphanRemoval = true, mappedBy = "parentItem")
    @OrderBy("sortOrder ASC")
    protected Set<Navigation> items;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getLocaleText() {
        return this.localeText;
    }

    public void setLocaleText(String localeText) {
        this.localeText = localeText;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getLocaleTitle() {
        return this.localeTitle;
    }

    public void setLocaleTitle(String localeTitle) {
        this.localeTitle = localeTitle;
    }

    public String getCssClass() {
        return this.cssClass;
    }

    public void setCssClass(String cssClass) {
        this.cssClass = cssClass;
    }

    public String getStyles() {
        return this.styles;
    }

    public void setStyles(String styles) {
        this.styles = styles;
    }

    public String getLinkUrl() {
        return this.linkUrl;
    }

    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl;
    }

    public String getLinkTitle() {
        return this.linkTitle;
    }

    public void setLinkTitle(String linkTitle) {
        this.linkTitle = linkTitle;
    }

    public String getLinkLocaleTitle() {
        return this.linkLocaleTitle;
    }

    public void setLinkLocaleTitle(String linkLocaleTitle) {
        this.linkLocaleTitle = linkLocaleTitle;
    }

    public String getLinkCssClass() {
        return this.linkCssClass;
    }

    public void setLinkCssClass(String linkCssClass) {
        this.linkCssClass = linkCssClass;
    }

    public String getLinkStyles() {
        return this.linkStyles;
    }

    public void setLinkStyles(String linkStyles) {
        this.linkStyles = linkStyles;
    }

    public String getRoles() {
        return this.roles;
    }

    public void setRoles(String roles) {
        this.roles = roles;
    }

    public String getUsers() {
        return this.users;
    }

    public void setUsers(String users) {
        this.users = users;
    }

    public Integer getSortOrder() {
        return this.sortOrder;
    }

    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    public Boolean isAuthMode() {
        return this.authMode;
    }

    public void setAuthMode(Boolean authMode) {
        this.authMode = authMode;
    }

    public Boolean isSeparator() {
        return this.separator;
    }

    public void setSeparator(Boolean separator) {
        this.separator = separator;
    }

    public Long getNavigationMenuId() {
        return this.navigationMenuId;
    }

    public void setNavigationMenuId(Long navigationMenuId) {
        this.navigationMenuId = navigationMenuId;
    }

    public Long getParentId() {
        return this.parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public NavigationMenu getMenu() {
        return this.menu;
    }

    public void setMenu(NavigationMenu menu) {
        this.menu = menu;
    }

    public Navigation getParentItem() {
        return this.parentItem;
    }

    public void setParentItem(Navigation parentItem) {
        this.parentItem = parentItem;
    }

    public Set<Navigation> getItems() {
        return this.items;
    }

    public void setItems(Set<Navigation> items) {
        this.items = items;
    }

}