//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Core.Navigations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Navigation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Navigation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Core.Navigations.Navigation", typeof(Navigation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNTS.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts.
        /// </summary>
        public static string AccountsD {
            get {
                return ResourceManager.GetString("AccountsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVITY HISTORY.
        /// </summary>
        public static string ActivityHistory {
            get {
                return ResourceManager.GetString("ActivityHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activity history.
        /// </summary>
        public static string ActivityHistoryD {
            get {
                return ResourceManager.GetString("ActivityHistoryD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT SETTINGS.
        /// </summary>
        public static string AdminAccountSettings {
            get {
                return ResourceManager.GetString("AdminAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account settings.
        /// </summary>
        public static string AdminAccountSettingsD {
            get {
                return ResourceManager.GetString("AdminAccountSettingsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE ADS.
        /// </summary>
        public static string AdminAds {
            get {
                return ResourceManager.GetString("AdminAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage advertisements.
        /// </summary>
        public static string AdminAdsD {
            get {
                return ResourceManager.GetString("AdminAdsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP SETTINGS.
        /// </summary>
        public static string AdminAppSettings {
            get {
                return ResourceManager.GetString("AdminAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application settings.
        /// </summary>
        public static string AdminAppSettingsD {
            get {
                return ResourceManager.GetString("AdminAppSettingsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERAL SETTINGS.
        /// </summary>
        public static string AdminGeneralSettings {
            get {
                return ResourceManager.GetString("AdminGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general settings.
        /// </summary>
        public static string AdminGeneralSettingsD {
            get {
                return ResourceManager.GetString("AdminGeneralSettingsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN HISTORY.
        /// </summary>
        public static string AdminLoginHistory {
            get {
                return ResourceManager.GetString("AdminLoginHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login history.
        /// </summary>
        public static string AdminLoginHistoryD {
            get {
                return ResourceManager.GetString("AdminLoginHistoryD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE NEWS.
        /// </summary>
        public static string AdminNews {
            get {
                return ResourceManager.GetString("AdminNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage news.
        /// </summary>
        public static string AdminNewsD {
            get {
                return ResourceManager.GetString("AdminNewsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE TRANSACTIONS.
        /// </summary>
        public static string AdminTransactions {
            get {
                return ResourceManager.GetString("AdminTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage transactions.
        /// </summary>
        public static string AdminTransactionsD {
            get {
                return ResourceManager.GetString("AdminTransactionsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE USERS.
        /// </summary>
        public static string AdminUsers {
            get {
                return ResourceManager.GetString("AdminUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage users.
        /// </summary>
        public static string AdminUsersD {
            get {
                return ResourceManager.GetString("AdminUsersD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADVERTISEMENTS.
        /// </summary>
        public static string Advertisements {
            get {
                return ResourceManager.GetString("Advertisements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advertisements.
        /// </summary>
        public static string AdvertisementsD {
            get {
                return ResourceManager.GetString("AdvertisementsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All News.
        /// </summary>
        public static string AllNews {
            get {
                return ResourceManager.GetString("AllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All News.
        /// </summary>
        public static string AllNewsD {
            get {
                return ResourceManager.GetString("AllNewsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string Cell {
            get {
                return ResourceManager.GetString("Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANIES.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage companies.
        /// </summary>
        public static string CompaniesD {
            get {
                return ResourceManager.GetString("CompaniesD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact information.
        /// </summary>
        public static string ContactD {
            get {
                return ResourceManager.GetString("ContactD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERAL LISTS.
        /// </summary>
        public static string GeneralLists {
            get {
                return ResourceManager.GetString("GeneralLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string HelpAbout {
            get {
                return ResourceManager.GetString("HelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string HelpAboutD {
            get {
                return ResourceManager.GetString("HelpAboutD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help information.
        /// </summary>
        public static string HelpD {
            get {
                return ResourceManager.GetString("HelpD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER MANUAL.
        /// </summary>
        public static string HelpManual {
            get {
                return ResourceManager.GetString("HelpManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user manual.
        /// </summary>
        public static string HelpManualD {
            get {
                return ResourceManager.GetString("HelpManualD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        public static string HomeD {
            get {
                return ResourceManager.GetString("HomeD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change language.
        /// </summary>
        public static string LanguageD {
            get {
                return ResourceManager.GetString("LanguageD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGLISH.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display website in english.
        /// </summary>
        public static string LanguageEnglishD {
            get {
                return ResourceManager.GetString("LanguageEnglishD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اردو.
        /// </summary>
        public static string LanguageUrdu {
            get {
                return ResourceManager.GetString("LanguageUrdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویب سائٹ اردو زبان میںدیکھیں.
        /// </summary>
        public static string LanguageUrduD {
            get {
                return ResourceManager.GetString("LanguageUrduD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY ACCOUNT.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my account.
        /// </summary>
        public static string MyAccountD {
            get {
                return ResourceManager.GetString("MyAccountD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN HISTORY.
        /// </summary>
        public static string MyAccountHistory {
            get {
                return ResourceManager.GetString("MyAccountHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login history.
        /// </summary>
        public static string MyAccountHistoryD {
            get {
                return ResourceManager.GetString("MyAccountHistoryD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER PROFILE.
        /// </summary>
        public static string MyAccountProfile {
            get {
                return ResourceManager.GetString("MyAccountProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user profile.
        /// </summary>
        public static string MyAccountProfileD {
            get {
                return ResourceManager.GetString("MyAccountProfileD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLICATION.
        /// </summary>
        public static string MyApplication {
            get {
                return ResourceManager.GetString("MyApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application.
        /// </summary>
        public static string MyApplicationD {
            get {
                return ResourceManager.GetString("MyApplicationD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORIES.
        /// </summary>
        public static string MyCategories {
            get {
                return ResourceManager.GetString("MyCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage categories.
        /// </summary>
        public static string MyCategoriesD {
            get {
                return ResourceManager.GetString("MyCategoriesD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLORS.
        /// </summary>
        public static string MyColors {
            get {
                return ResourceManager.GetString("MyColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage colors.
        /// </summary>
        public static string MyColorsD {
            get {
                return ResourceManager.GetString("MyColorsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMERS.
        /// </summary>
        public static string MyCustomers {
            get {
                return ResourceManager.GetString("MyCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage customers.
        /// </summary>
        public static string MyCustomersD {
            get {
                return ResourceManager.GetString("MyCustomersD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALLMENTS.
        /// </summary>
        public static string MyInstallments {
            get {
                return ResourceManager.GetString("MyInstallments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage installments.
        /// </summary>
        public static string MyInstallmentsD {
            get {
                return ResourceManager.GetString("MyInstallmentsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISTS.
        /// </summary>
        public static string MyLists {
            get {
                return ResourceManager.GetString("MyLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lists.
        /// </summary>
        public static string MyListsD {
            get {
                return ResourceManager.GetString("MyListsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANUFACTURERS.
        /// </summary>
        public static string MyManufacturers {
            get {
                return ResourceManager.GetString("MyManufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage manufacturers.
        /// </summary>
        public static string MyManufacturersD {
            get {
                return ResourceManager.GetString("MyManufacturersD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW PURCHASE.
        /// </summary>
        public static string MyNewPurchase {
            get {
                return ResourceManager.GetString("MyNewPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchase new product.
        /// </summary>
        public static string MyNewPurchaseD {
            get {
                return ResourceManager.GetString("MyNewPurchaseD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW SALE.
        /// </summary>
        public static string MyNewSale {
            get {
                return ResourceManager.GetString("MyNewSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sale a product.
        /// </summary>
        public static string MyNewSaleD {
            get {
                return ResourceManager.GetString("MyNewSaleD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCTS.
        /// </summary>
        public static string MyProducts {
            get {
                return ResourceManager.GetString("MyProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage products.
        /// </summary>
        public static string MyProductsD {
            get {
                return ResourceManager.GetString("MyProductsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASH REPORT.
        /// </summary>
        public static string MyReportCash {
            get {
                return ResourceManager.GetString("MyReportCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display cash report.
        /// </summary>
        public static string MyReportCashD {
            get {
                return ResourceManager.GetString("MyReportCashD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDIT REPORT.
        /// </summary>
        public static string MyReportCredit {
            get {
                return ResourceManager.GetString("MyReportCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display credit report.
        /// </summary>
        public static string MyReportCreditD {
            get {
                return ResourceManager.GetString("MyReportCreditD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURSTOMERS REPORT.
        /// </summary>
        public static string MyReportCustomers {
            get {
                return ResourceManager.GetString("MyReportCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display customers report.
        /// </summary>
        public static string MyReportCustomersD {
            get {
                return ResourceManager.GetString("MyReportCustomersD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCOME REPORT.
        /// </summary>
        public static string MyReportIncome {
            get {
                return ResourceManager.GetString("MyReportIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display income report.
        /// </summary>
        public static string MyReportIncomeD {
            get {
                return ResourceManager.GetString("MyReportIncomeD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVENTORY REPORT.
        /// </summary>
        public static string MyReportInventory {
            get {
                return ResourceManager.GetString("MyReportInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display inventory report.
        /// </summary>
        public static string MyReportInventoryD {
            get {
                return ResourceManager.GetString("MyReportInventoryD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PURCHASES REPORT.
        /// </summary>
        public static string MyReportPurchases {
            get {
                return ResourceManager.GetString("MyReportPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display purchases report.
        /// </summary>
        public static string MyReportPurchasesD {
            get {
                return ResourceManager.GetString("MyReportPurchasesD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORTS.
        /// </summary>
        public static string MyReports {
            get {
                return ResourceManager.GetString("MyReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALES REPORT.
        /// </summary>
        public static string MyReportSales {
            get {
                return ResourceManager.GetString("MyReportSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display sales report.
        /// </summary>
        public static string MyReportSalesD {
            get {
                return ResourceManager.GetString("MyReportSalesD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reports.
        /// </summary>
        public static string MyReportsD {
            get {
                return ResourceManager.GetString("MyReportsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSACTIONS REPORT.
        /// </summary>
        public static string MyReportTransactions {
            get {
                return ResourceManager.GetString("MyReportTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display transactions report.
        /// </summary>
        public static string MyReportTransactionsD {
            get {
                return ResourceManager.GetString("MyReportTransactionsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSACTIONS.
        /// </summary>
        public static string MyTransactions {
            get {
                return ResourceManager.GetString("MyTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage transactions.
        /// </summary>
        public static string MyTransactionsD {
            get {
                return ResourceManager.GetString("MyTransactionsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITS.
        /// </summary>
        public static string MyUnits {
            get {
                return ResourceManager.GetString("MyUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage units.
        /// </summary>
        public static string MyUnitsD {
            get {
                return ResourceManager.GetString("MyUnitsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news.
        /// </summary>
        public static string NewsD {
            get {
                return ResourceManager.GetString("NewsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCTS.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products.
        /// </summary>
        public static string ProductsD {
            get {
                return ResourceManager.GetString("ProductsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFERENCES.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string ReferenceD {
            get {
                return ResourceManager.GetString("ReferenceD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROLES.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roles.
        /// </summary>
        public static string RolesD {
            get {
                return ResourceManager.GetString("RolesD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE.
        /// </summary>
        public static string Sdk {
            get {
                return ResourceManager.GetString("Sdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMBER TYPE.
        /// </summary>
        public static string SdkComponentMemberType {
            get {
                return ResourceManager.GetString("SdkComponentMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to component member type.
        /// </summary>
        public static string SdkComponentMemberTypeD {
            get {
                return ResourceManager.GetString("SdkComponentMemberTypeD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to software information.
        /// </summary>
        public static string SdkD {
            get {
                return ResourceManager.GetString("SdkD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFERENCES.
        /// </summary>
        public static string SdkReferences {
            get {
                return ResourceManager.GetString("SdkReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in to website.
        /// </summary>
        public static string SignInD {
            get {
                return ResourceManager.GetString("SignInD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN OUT.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign out of website.
        /// </summary>
        public static string SignOutD {
            get {
                return ResourceManager.GetString("SignOutD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string UsefulLinksD {
            get {
                return ResourceManager.GetString("UsefulLinksD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
