//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Views.Product {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Views.Product.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category.
        /// </summary>
        public static string CategoryD {
            get {
                return ResourceManager.GetString("CategoryD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact here..
        /// </summary>
        public static string ContactT {
            get {
                return ResourceManager.GetString("ContactT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available for sale.
        /// </summary>
        public static string ForSaleT {
            get {
                return ResourceManager.GetString("ForSaleT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manufacturer.
        /// </summary>
        public static string ManufacturerD {
            get {
                return ResourceManager.GetString("ManufacturerD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string ModelYearD {
            get {
                return ResourceManager.GetString("ModelYearD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following products are available for sale. For inquiries kindly .
        /// </summary>
        public static string PageD {
            get {
                return ResourceManager.GetString("PageD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string PageT {
            get {
                return ResourceManager.GetString("PageT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price.
        /// </summary>
        public static string PriceD {
            get {
                return ResourceManager.GetString("PriceD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product name.
        /// </summary>
        public static string ProductNameD {
            get {
                return ResourceManager.GetString("ProductNameD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horse power.
        /// </summary>
        public static string UnitD {
            get {
                return ResourceManager.GetString("UnitD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to products page..
        /// </summary>
        public static string WelcomeT {
            get {
                return ResourceManager.GetString("WelcomeT", resourceCulture);
            }
        }
    }
}
