//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocaleResources.Core.Contents.Stock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StockProduct {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StockProduct() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocaleResources.Core.Contents.Stock.StockProduct", typeof(StockProduct).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chasis.
        /// </summary>
        public static string ChasisNo {
            get {
                return ResourceManager.GetString("ChasisNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine.
        /// </summary>
        public static string EngineNo {
            get {
                return ResourceManager.GetString("EngineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Date.
        /// </summary>
        public static string LegalDate {
            get {
                return ResourceManager.GetString("LegalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Name.
        /// </summary>
        public static string LegalName {
            get {
                return ResourceManager.GetString("LegalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner ID.
        /// </summary>
        public static string OwnerID {
            get {
                return ResourceManager.GetString("OwnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string SerialNo {
            get {
                return ResourceManager.GetString("SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock ID.
        /// </summary>
        public static string StockID {
            get {
                return ResourceManager.GetString("StockID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID.
        /// </summary>
        public static string UID {
            get {
                return ResourceManager.GetString("UID", resourceCulture);
            }
        }
    }
}
