//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Core.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Contact {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contact() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Core.Views.Home.Contact", typeof(Contact).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours.
        /// </summary>
        public static string BusinessHoursT {
            get {
                return ResourceManager.GetString("BusinessHoursT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter captcha text here..
        /// </summary>
        public static string CaptchaD {
            get {
                return ResourceManager.GetString("CaptchaD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha input does not match the image displayed..
        /// </summary>
        public static string CaptchaErrorD {
            get {
                return ResourceManager.GetString("CaptchaErrorD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha text - click to change..
        /// </summary>
        public static string CaptchaImageD {
            get {
                return ResourceManager.GetString("CaptchaImageD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha text.
        /// </summary>
        public static string CaptchaT {
            get {
                return ResourceManager.GetString("CaptchaT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear visitor you can contact us by writing to the address written below..
        /// </summary>
        public static string ContactD {
            get {
                return ResourceManager.GetString("ContactD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactT {
            get {
                return ResourceManager.GetString("ContactT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send your inquiries by submitting following form..
        /// </summary>
        public static string FormContactD {
            get {
                return ResourceManager.GetString("FormContactD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Now.
        /// </summary>
        public static string FormContactNowT {
            get {
                return ResourceManager.GetString("FormContactNowT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Form.
        /// </summary>
        public static string FormContactT {
            get {
                return ResourceManager.GetString("FormContactT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string FormEmailT {
            get {
                return ResourceManager.GetString("FormEmailT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string FormMessageT {
            get {
                return ResourceManager.GetString("FormMessageT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FormNameT {
            get {
                return ResourceManager.GetString("FormNameT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string FormSubjectT {
            get {
                return ResourceManager.GetString("FormSubjectT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string OfficeLocationT {
            get {
                return ResourceManager.GetString("OfficeLocationT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PageD {
            get {
                return ResourceManager.GetString("PageD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string PageT {
            get {
                return ResourceManager.GetString("PageT", resourceCulture);
            }
        }
    }
}
