USE [master]
GO
/****** Object:  Database [webapplication7]    Script Date: 6/11/2022 1:53:14 PM ******/
CREATE DATABASE [webapplication7]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'webapplication7', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\webapplication7.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'webapplication7_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\webapplication7_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [webapplication7] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [webapplication7].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [webapplication7] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [webapplication7] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [webapplication7] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [webapplication7] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [webapplication7] SET ARITHABORT OFF 
GO
ALTER DATABASE [webapplication7] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [webapplication7] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [webapplication7] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [webapplication7] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [webapplication7] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [webapplication7] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [webapplication7] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [webapplication7] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [webapplication7] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [webapplication7] SET  DISABLE_BROKER 
GO
ALTER DATABASE [webapplication7] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [webapplication7] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [webapplication7] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [webapplication7] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [webapplication7] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [webapplication7] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [webapplication7] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [webapplication7] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [webapplication7] SET  MULTI_USER 
GO
ALTER DATABASE [webapplication7] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [webapplication7] SET DB_CHAINING OFF 
GO
ALTER DATABASE [webapplication7] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [webapplication7] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [webapplication7] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [webapplication7] SET QUERY_STORE = OFF
GO
USE [webapplication7]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 6/11/2022 1:53:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 6/11/2022 1:53:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[UID] [uniqueidentifier] NOT NULL,
	[Description] [nvarchar](max) NULL,
	[Name] [nvarchar](max) NULL,
	[RowVersion] [varbinary](max) NULL,
 CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
(
	[UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Colors]    Script Date: 6/11/2022 1:53:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Colors](
	[UID] [uniqueidentifier] NOT NULL,
	[Description] [nvarchar](max) NULL,
	[Name] [nvarchar](max) NULL,
	[RowVersion] [varbinary](max) NULL,
 CONSTRAINT [PK_Colors] PRIMARY KEY CLUSTERED 
(
	[UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employees]    Script Date: 6/11/2022 1:53:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employees](
	[Id] [nvarchar](450) NOT NULL,
	[Designation] [nvarchar](max) NULL,
	[Name] [nvarchar](max) NULL,
	[Salary] [decimal](18, 2) NULL,
 CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Units]    Script Date: 6/11/2022 1:53:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Units](
	[UID] [uniqueidentifier] NOT NULL,
	[Description] [nvarchar](max) NULL,
	[Name] [nvarchar](max) NULL,
	[RowVersion] [varbinary](max) NULL,
 CONSTRAINT [PK_Units] PRIMARY KEY CLUSTERED 
(
	[UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [webapplication7] SET  READ_WRITE 
GO
