//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public System.Guid UID { get; set; }
        public Nullable<System.Guid> ReferenceID { get; set; }
        public System.DateTime RecordTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Heading { get; set; }
        public string SubHeading { get; set; }
        public string Detail { get; set; }
        public string Picture { get; set; }
        public string Video { get; set; }
        public string Link1 { get; set; }
        public string Link2 { get; set; }
        public string Source { get; set; }
        public string Page { get; set; }
        public string Location { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> News { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
