//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public System.Guid UID { get; set; }
        public string LegalCode { get; set; }
        public string NTN { get; set; }
        public string STRN { get; set; }
        public string LegalName { get; set; }
        public string CompanyType { get; set; }
        public string Description { get; set; }
        public string Director { get; set; }
        public string Secretary { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Cell1 { get; set; }
        public string Cell2 { get; set; }
        public string Email { get; set; }
        public Nullable<long> PaidUpCapital { get; set; }
        public string Currency { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonDesignation { get; set; }
        public string ContactPersonPhone { get; set; }
        public string ContactPersonCell { get; set; }
        public string ContactPersonEmail { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
