//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseInfo
    {
        public System.Guid ProductID { get; set; }
        public string Code { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
