//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reference
    {
        public System.Guid UID { get; set; }
        public Nullable<System.Guid> ReferenceID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ContentFile { get; set; }
        public byte[] ContentBytes { get; set; }
        public long Size { get; set; }
        public Nullable<bool> Readable { get; set; }
        public Nullable<bool> Picture { get; set; }
        public Nullable<bool> AudioVideo { get; set; }
        public bool Download { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
