//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public System.Guid UID { get; set; }
        public System.DateTime RegistrationTime { get; set; }
        public string UserID { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string PCode { get; set; }
        public string HID { get; set; }
        public string LicenseTypeID { get; set; }
        public Nullable<int> Period { get; set; }
        public string CCard { get; set; }
        public Nullable<int> CCardYear { get; set; }
        public Nullable<int> CCardMonth { get; set; }
        public string CVV { get; set; }
        public Nullable<int> Cost { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<long> OrderNumber { get; set; }
        public Nullable<long> TransactionID { get; set; }
        public Nullable<bool> Licensed { get; set; }
        public Nullable<System.DateTime> LicenseTime { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
