//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid UID { get; set; }
        public System.Guid CompositeID { get; set; }
        public System.DateTime TransactionTime { get; set; }
        public string AccountID { get; set; }
        public string Title { get; set; }
        public string Particulars { get; set; }
        public decimal DrAmount { get; set; }
        public decimal CrAmount { get; set; }
        public int Quantity { get; set; }
        public bool Active { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
