//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocaleResources.Views.User {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocaleResources.Views.User.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        public static string ApprovedBy {
            get {
                return ResourceManager.GetString("ApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approved by.
        /// </summary>
        public static string ApprovedByD {
            get {
                return ResourceManager.GetString("ApprovedByD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select if approved.
        /// </summary>
        public static string ApprovedD {
            get {
                return ResourceManager.GetString("ApprovedD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Roles.
        /// </summary>
        public static string AssignedRoles {
            get {
                return ResourceManager.GetString("AssignedRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display roles attached to account.
        /// </summary>
        public static string AssignedRolesD {
            get {
                return ResourceManager.GetString("AssignedRolesD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Roles.
        /// </summary>
        public static string AvailableRoles {
            get {
                return ResourceManager.GetString("AvailableRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display available roles.
        /// </summary>
        public static string AvailableRolesD {
            get {
                return ResourceManager.GetString("AvailableRolesD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter confirmation password here.
        /// </summary>
        public static string ConfirmD {
            get {
                return ResourceManager.GetString("ConfirmD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate your account..
        /// </summary>
        public static string EmailAccountActivationSubject {
            get {
                return ResourceManager.GetString("EmailAccountActivationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Activation Email.
        /// </summary>
        public static string EmailAccountActivationTitle {
            get {
                return ResourceManager.GetString("EmailAccountActivationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmed.
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select if email confirmed.
        /// </summary>
        public static string EmailConfirmedD {
            get {
                return ResourceManager.GetString("EmailConfirmedD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter email here.
        /// </summary>
        public static string EmailD {
            get {
                return ResourceManager.GetString("EmailD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry.
        /// </summary>
        public static string Expiry {
            get {
                return ResourceManager.GetString("Expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter account expiry date.
        /// </summary>
        public static string ExpiryD {
            get {
                return ResourceManager.GetString("ExpiryD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter first name here.
        /// </summary>
        public static string FirstNameD {
            get {
                return ResourceManager.GetString("FirstNameD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Form.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select gender.
        /// </summary>
        public static string GenderD {
            get {
                return ResourceManager.GetString("GenderD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter last name here.
        /// </summary>
        public static string LastNameD {
            get {
                return ResourceManager.GetString("LastNameD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display name.
        /// </summary>
        public static string NameD {
            get {
                return ResourceManager.GetString("NameD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter package here.
        /// </summary>
        public static string PackageD {
            get {
                return ResourceManager.GetString("PackageD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is user management page..
        /// </summary>
        public static string PageD {
            get {
                return ResourceManager.GetString("PageD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter password here.
        /// </summary>
        public static string PasswordD {
            get {
                return ResourceManager.GetString("PasswordD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display picture.
        /// </summary>
        public static string PictureD {
            get {
                return ResourceManager.GetString("PictureD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attached roles.
        /// </summary>
        public static string RolesD {
            get {
                return ResourceManager.GetString("RolesD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account registration time.
        /// </summary>
        public static string TimeD {
            get {
                return ResourceManager.GetString("TimeD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter title here.
        /// </summary>
        public static string TitleD {
            get {
                return ResourceManager.GetString("TitleD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account username.
        /// </summary>
        public static string UserD {
            get {
                return ResourceManager.GetString("UserD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user identification record.
        /// </summary>
        public static string UserIdD {
            get {
                return ResourceManager.GetString("UserIdD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter user name here.
        /// </summary>
        public static string UserNameD {
            get {
                return ResourceManager.GetString("UserNameD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to user management page..
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
