//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Navigations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Navigation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Navigation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Navigations.Navigation", typeof(Navigation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNTS.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts.
        /// </summary>
        public static string AccountsD {
            get {
                return ResourceManager.GetString("AccountsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact information.
        /// </summary>
        public static string AContactD {
            get {
                return ResourceManager.GetString("AContactD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT.
        /// </summary>
        public static string AContactT {
            get {
                return ResourceManager.GetString("AContactT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account settings.
        /// </summary>
        public static string AdminAccountSettingsD {
            get {
                return ResourceManager.GetString("AdminAccountSettingsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT SETTINGS.
        /// </summary>
        public static string AdminAccountSettingsT {
            get {
                return ResourceManager.GetString("AdminAccountSettingsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage advertisements.
        /// </summary>
        public static string AdminAdsD {
            get {
                return ResourceManager.GetString("AdminAdsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE ADS.
        /// </summary>
        public static string AdminAdsT {
            get {
                return ResourceManager.GetString("AdminAdsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application settings.
        /// </summary>
        public static string AdminAppSettingsD {
            get {
                return ResourceManager.GetString("AdminAppSettingsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP SETTINGS.
        /// </summary>
        public static string AdminAppSettingsT {
            get {
                return ResourceManager.GetString("AdminAppSettingsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general settings.
        /// </summary>
        public static string AdminGeneralSettingsD {
            get {
                return ResourceManager.GetString("AdminGeneralSettingsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERAL SETTINGS.
        /// </summary>
        public static string AdminGeneralSettingsT {
            get {
                return ResourceManager.GetString("AdminGeneralSettingsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login history.
        /// </summary>
        public static string AdminLoginHistoryD {
            get {
                return ResourceManager.GetString("AdminLoginHistoryD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN HISTORY.
        /// </summary>
        public static string AdminLoginHistoryT {
            get {
                return ResourceManager.GetString("AdminLoginHistoryT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage news.
        /// </summary>
        public static string AdminNewsD {
            get {
                return ResourceManager.GetString("AdminNewsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE NEWS.
        /// </summary>
        public static string AdminNewsT {
            get {
                return ResourceManager.GetString("AdminNewsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage transactions.
        /// </summary>
        public static string AdminTransactionsD {
            get {
                return ResourceManager.GetString("AdminTransactionsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE TRANSACTIONS.
        /// </summary>
        public static string AdminTransactionsT {
            get {
                return ResourceManager.GetString("AdminTransactionsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage users.
        /// </summary>
        public static string AdminUsersD {
            get {
                return ResourceManager.GetString("AdminUsersD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE USERS.
        /// </summary>
        public static string AdminUsersT {
            get {
                return ResourceManager.GetString("AdminUsersT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advertisements.
        /// </summary>
        public static string AdvertisementsD {
            get {
                return ResourceManager.GetString("AdvertisementsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADVERTISEMENTS.
        /// </summary>
        public static string AdvertisementsT {
            get {
                return ResourceManager.GetString("AdvertisementsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AHelpAboutD {
            get {
                return ResourceManager.GetString("AHelpAboutD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string AHelpAboutT {
            get {
                return ResourceManager.GetString("AHelpAboutT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help information.
        /// </summary>
        public static string AHelpD {
            get {
                return ResourceManager.GetString("AHelpD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user manual.
        /// </summary>
        public static string AHelpManualD {
            get {
                return ResourceManager.GetString("AHelpManualD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER MANUAL.
        /// </summary>
        public static string AHelpManualT {
            get {
                return ResourceManager.GetString("AHelpManualT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        public static string AHelpT {
            get {
                return ResourceManager.GetString("AHelpT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        public static string AHomeD {
            get {
                return ResourceManager.GetString("AHomeD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string AHomeT {
            get {
                return ResourceManager.GetString("AHomeT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change language.
        /// </summary>
        public static string ALanguageD {
            get {
                return ResourceManager.GetString("ALanguageD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display website in english.
        /// </summary>
        public static string ALanguageEnglishD {
            get {
                return ResourceManager.GetString("ALanguageEnglishD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGLISH.
        /// </summary>
        public static string ALanguageEnglishT {
            get {
                return ResourceManager.GetString("ALanguageEnglishT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE.
        /// </summary>
        public static string ALanguageT {
            get {
                return ResourceManager.GetString("ALanguageT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویب سائٹ اردو زبان میںدیکھیں.
        /// </summary>
        public static string ALanguageUrduD {
            get {
                return ResourceManager.GetString("ALanguageUrduD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اردو.
        /// </summary>
        public static string ALanguageUrduT {
            get {
                return ResourceManager.GetString("ALanguageUrduT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All News.
        /// </summary>
        public static string AllNewsD {
            get {
                return ResourceManager.GetString("AllNewsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All News.
        /// </summary>
        public static string AllNewsT {
            get {
                return ResourceManager.GetString("AllNewsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news.
        /// </summary>
        public static string ANewsD {
            get {
                return ResourceManager.GetString("ANewsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS.
        /// </summary>
        public static string ANewsT {
            get {
                return ResourceManager.GetString("ANewsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products.
        /// </summary>
        public static string AProductsD {
            get {
                return ResourceManager.GetString("AProductsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCTS.
        /// </summary>
        public static string AProductsT {
            get {
                return ResourceManager.GetString("AProductsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in to website.
        /// </summary>
        public static string ASignInD {
            get {
                return ResourceManager.GetString("ASignInD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string ASignInT {
            get {
                return ResourceManager.GetString("ASignInT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign out of website.
        /// </summary>
        public static string ASignOutD {
            get {
                return ResourceManager.GetString("ASignOutD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN OUT.
        /// </summary>
        public static string ASignOutT {
            get {
                return ResourceManager.GetString("ASignOutT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string CellT {
            get {
                return ResourceManager.GetString("CellT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANIES.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage companies.
        /// </summary>
        public static string CompaniesD {
            get {
                return ResourceManager.GetString("CompaniesD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailT {
            get {
                return ResourceManager.GetString("EmailT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERAL LISTS.
        /// </summary>
        public static string GeneralListsT {
            get {
                return ResourceManager.GetString("GeneralListsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my account.
        /// </summary>
        public static string MyAccountD {
            get {
                return ResourceManager.GetString("MyAccountD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login history.
        /// </summary>
        public static string MyAccountHistoryD {
            get {
                return ResourceManager.GetString("MyAccountHistoryD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN HISTORY.
        /// </summary>
        public static string MyAccountHistoryT {
            get {
                return ResourceManager.GetString("MyAccountHistoryT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user profile.
        /// </summary>
        public static string MyAccountProfileD {
            get {
                return ResourceManager.GetString("MyAccountProfileD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER PROFILE.
        /// </summary>
        public static string MyAccountProfileT {
            get {
                return ResourceManager.GetString("MyAccountProfileT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY ACCOUNT.
        /// </summary>
        public static string MyAccountT {
            get {
                return ResourceManager.GetString("MyAccountT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application.
        /// </summary>
        public static string MyApplicationD {
            get {
                return ResourceManager.GetString("MyApplicationD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLICATION.
        /// </summary>
        public static string MyApplicationT {
            get {
                return ResourceManager.GetString("MyApplicationT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage categories.
        /// </summary>
        public static string MyCategoriesD {
            get {
                return ResourceManager.GetString("MyCategoriesD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORIES.
        /// </summary>
        public static string MyCategoriesT {
            get {
                return ResourceManager.GetString("MyCategoriesT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage colors.
        /// </summary>
        public static string MyColorsD {
            get {
                return ResourceManager.GetString("MyColorsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLORS.
        /// </summary>
        public static string MyColorsT {
            get {
                return ResourceManager.GetString("MyColorsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage customers.
        /// </summary>
        public static string MyCustomersD {
            get {
                return ResourceManager.GetString("MyCustomersD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMERS.
        /// </summary>
        public static string MyCustomersT {
            get {
                return ResourceManager.GetString("MyCustomersT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage installments.
        /// </summary>
        public static string MyInstallmentsD {
            get {
                return ResourceManager.GetString("MyInstallmentsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALLMENTS.
        /// </summary>
        public static string MyInstallmentsT {
            get {
                return ResourceManager.GetString("MyInstallmentsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lists.
        /// </summary>
        public static string MyListsD {
            get {
                return ResourceManager.GetString("MyListsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISTS.
        /// </summary>
        public static string MyListsT {
            get {
                return ResourceManager.GetString("MyListsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage manufacturers.
        /// </summary>
        public static string MyManufacturersD {
            get {
                return ResourceManager.GetString("MyManufacturersD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANUFACTURERS.
        /// </summary>
        public static string MyManufacturersT {
            get {
                return ResourceManager.GetString("MyManufacturersT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchase new product.
        /// </summary>
        public static string MyNewPurchaseD {
            get {
                return ResourceManager.GetString("MyNewPurchaseD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW PURCHASE.
        /// </summary>
        public static string MyNewPurchaseT {
            get {
                return ResourceManager.GetString("MyNewPurchaseT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sale a product.
        /// </summary>
        public static string MyNewSaleD {
            get {
                return ResourceManager.GetString("MyNewSaleD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW SALE.
        /// </summary>
        public static string MyNewSaleT {
            get {
                return ResourceManager.GetString("MyNewSaleT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage products.
        /// </summary>
        public static string MyProductsD {
            get {
                return ResourceManager.GetString("MyProductsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCTS.
        /// </summary>
        public static string MyProductsT {
            get {
                return ResourceManager.GetString("MyProductsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display cash report.
        /// </summary>
        public static string MyReportCashD {
            get {
                return ResourceManager.GetString("MyReportCashD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASH REPORT.
        /// </summary>
        public static string MyReportCashT {
            get {
                return ResourceManager.GetString("MyReportCashT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display credit report.
        /// </summary>
        public static string MyReportCreditD {
            get {
                return ResourceManager.GetString("MyReportCreditD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDIT REPORT.
        /// </summary>
        public static string MyReportCreditT {
            get {
                return ResourceManager.GetString("MyReportCreditT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display customers report.
        /// </summary>
        public static string MyReportCustomersD {
            get {
                return ResourceManager.GetString("MyReportCustomersD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURSTOMERS REPORT.
        /// </summary>
        public static string MyReportCustomersT {
            get {
                return ResourceManager.GetString("MyReportCustomersT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display income report.
        /// </summary>
        public static string MyReportIncomeD {
            get {
                return ResourceManager.GetString("MyReportIncomeD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCOME REPORT.
        /// </summary>
        public static string MyReportIncomeT {
            get {
                return ResourceManager.GetString("MyReportIncomeT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display inventory report.
        /// </summary>
        public static string MyReportInventoryD {
            get {
                return ResourceManager.GetString("MyReportInventoryD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVENTORY REPORT.
        /// </summary>
        public static string MyReportInventoryT {
            get {
                return ResourceManager.GetString("MyReportInventoryT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display purchases report.
        /// </summary>
        public static string MyReportPurchasesD {
            get {
                return ResourceManager.GetString("MyReportPurchasesD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PURCHASES REPORT.
        /// </summary>
        public static string MyReportPurchasesT {
            get {
                return ResourceManager.GetString("MyReportPurchasesT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display sales report.
        /// </summary>
        public static string MyReportSalesD {
            get {
                return ResourceManager.GetString("MyReportSalesD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALES REPORT.
        /// </summary>
        public static string MyReportSalesT {
            get {
                return ResourceManager.GetString("MyReportSalesT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reports.
        /// </summary>
        public static string MyReportsD {
            get {
                return ResourceManager.GetString("MyReportsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORTS.
        /// </summary>
        public static string MyReportsT {
            get {
                return ResourceManager.GetString("MyReportsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display transactions report.
        /// </summary>
        public static string MyReportTransactionsD {
            get {
                return ResourceManager.GetString("MyReportTransactionsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSACTIONS REPORT.
        /// </summary>
        public static string MyReportTransactionsT {
            get {
                return ResourceManager.GetString("MyReportTransactionsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage transactions.
        /// </summary>
        public static string MyTransactionsD {
            get {
                return ResourceManager.GetString("MyTransactionsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSACTIONS.
        /// </summary>
        public static string MyTransactionsT {
            get {
                return ResourceManager.GetString("MyTransactionsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage units.
        /// </summary>
        public static string MyUnitsD {
            get {
                return ResourceManager.GetString("MyUnitsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITS.
        /// </summary>
        public static string MyUnitsT {
            get {
                return ResourceManager.GetString("MyUnitsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PhoneT {
            get {
                return ResourceManager.GetString("PhoneT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFERENCES.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string ReferenceD {
            get {
                return ResourceManager.GetString("ReferenceD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROLES.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roles.
        /// </summary>
        public static string RolesD {
            get {
                return ResourceManager.GetString("RolesD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE.
        /// </summary>
        public static string Sdk {
            get {
                return ResourceManager.GetString("Sdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMBER TYPE.
        /// </summary>
        public static string SdkComponentMemberType {
            get {
                return ResourceManager.GetString("SdkComponentMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to component member type.
        /// </summary>
        public static string SdkComponentMemberTypeD {
            get {
                return ResourceManager.GetString("SdkComponentMemberTypeD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to software information.
        /// </summary>
        public static string SdkD {
            get {
                return ResourceManager.GetString("SdkD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFERENCES.
        /// </summary>
        public static string SdkReferences {
            get {
                return ResourceManager.GetString("SdkReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string UsefulLinksD {
            get {
                return ResourceManager.GetString("UsefulLinksD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string UsefulLinksT {
            get {
                return ResourceManager.GetString("UsefulLinksT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeT {
            get {
                return ResourceManager.GetString("WelcomeT", resourceCulture);
            }
        }
    }
}
