//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Core.Resources.Global {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedLibrary.Core.Resources.Global.FormMessages", typeof(FormMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddD {
            get {
                return ResourceManager.GetString("AddD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display records in increasing order i.e. from lower to higher order.
        /// </summary>
        public static string AscendingD {
            get {
                return ResourceManager.GetString("AscendingD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha text.
        /// </summary>
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter captcha text here..
        /// </summary>
        public static string CaptchaD {
            get {
                return ResourceManager.GetString("CaptchaD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha input does not match the image displayed..
        /// </summary>
        public static string CaptchaErrorD {
            get {
                return ResourceManager.GetString("CaptchaErrorD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha text - click to change..
        /// </summary>
        public static string CaptchaImageD {
            get {
                return ResourceManager.GetString("CaptchaImageD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string Cell {
            get {
                return ResourceManager.GetString("Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteD {
            get {
                return ResourceManager.GetString("DeleteD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display records in decreasing order i.e. from higher to lower order.
        /// </summary>
        public static string DescendingD {
            get {
                return ResourceManager.GetString("DescendingD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying Page.
        /// </summary>
        public static string DisplayingPage {
            get {
                return ResourceManager.GetString("DisplayingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download content.
        /// </summary>
        public static string DownloadD {
            get {
                return ResourceManager.GetString("DownloadD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditD {
            get {
                return ResourceManager.GetString("EditD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E. Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end date.
        /// </summary>
        public static string EndDateD {
            get {
                return ResourceManager.GetString("EndDateD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E. Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end time.
        /// </summary>
        public static string EndTimeD {
            get {
                return ResourceManager.GetString("EndTimeD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string FieldDescription {
            get {
                return ResourceManager.GetString("FieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string FieldDescriptionD {
            get {
                return ResourceManager.GetString("FieldDescriptionD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string FieldNameD {
            get {
                return ResourceManager.GetString("FieldNameD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Detail.
        /// </summary>
        public static string FieldNewDetail {
            get {
                return ResourceManager.GetString("FieldNewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new detail.
        /// </summary>
        public static string FieldNewDetailD {
            get {
                return ResourceManager.GetString("FieldNewDetailD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Search.
        /// </summary>
        public static string HideSearch {
            get {
                return ResourceManager.GetString("HideSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string ImageUpload {
            get {
                return ResourceManager.GetString("ImageUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image View Form.
        /// </summary>
        public static string ImageViewForm {
            get {
                return ResourceManager.GetString("ImageViewForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter keyword here.
        /// </summary>
        public static string KeywordD {
            get {
                return ResourceManager.GetString("KeywordD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Size.
        /// </summary>
        public static string ListSize {
            get {
                return ResourceManager.GetString("ListSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list size.
        /// </summary>
        public static string ListSizeD {
            get {
                return ResourceManager.GetString("ListSizeD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewD {
            get {
                return ResourceManager.GetString("NewD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found..
        /// </summary>
        public static string NoRecord {
            get {
                return ResourceManager.GetString("NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PrevPage {
            get {
                return ResourceManager.GetString("PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record exists already..
        /// </summary>
        public static string RecordExists {
            get {
                return ResourceManager.GetString("RecordExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record(s).
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reload records.
        /// </summary>
        public static string ReloadD {
            get {
                return ResourceManager.GetString("ReloadD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is computer generated report and not valid for legal purposes..
        /// </summary>
        public static string ReportComputerGen {
            get {
                return ResourceManager.GetString("ReportComputerGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to press to search.
        /// </summary>
        public static string SearchD {
            get {
                return ResourceManager.GetString("SearchD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ....
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select from list.
        /// </summary>
        public static string SelectD {
            get {
                return ResourceManager.GetString("SelectD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Search.
        /// </summary>
        public static string ShowSearch {
            get {
                return ResourceManager.GetString("ShowSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/D Of.
        /// </summary>
        public static string SonOrDaughterOf {
            get {
                return ResourceManager.GetString("SonOrDaughterOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S. Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting date.
        /// </summary>
        public static string StartDateD {
            get {
                return ResourceManager.GetString("StartDateD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S. Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting time.
        /// </summary>
        public static string StartTimeD {
            get {
                return ResourceManager.GetString("StartTimeD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TotalPages {
            get {
                return ResourceManager.GetString("TotalPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select and upload content.
        /// </summary>
        public static string UploadD {
            get {
                return ResourceManager.GetString("UploadD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file, only limited size and extension files are allowed..
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image file, only *.jpg and *.png files are allowed..
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to useful links.
        /// </summary>
        public static string UsefulLinksD {
            get {
                return ResourceManager.GetString("UsefulLinksD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Video.
        /// </summary>
        public static string VideoUpload {
            get {
                return ResourceManager.GetString("VideoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video View Form.
        /// </summary>
        public static string VideoViewForm {
            get {
                return ResourceManager.GetString("VideoViewForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Image.
        /// </summary>
        public static string ViewImage {
            get {
                return ResourceManager.GetString("ViewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View New Window.
        /// </summary>
        public static string ViewInWindow {
            get {
                return ResourceManager.GetString("ViewInWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Video.
        /// </summary>
        public static string ViewVideo {
            get {
                return ResourceManager.GetString("ViewVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
