/**
 * This file was generated by the Jeddict
 */
package data.world;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

@Entity
@Table(name = "city")
@JsonIgnoreProperties
public class City {

    @Column(name = "ID", table = "city", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;

    @Column(name = "Name", table = "city", nullable = false, length = 35)
    @Basic(optional = false)
    private String name;

    @Column(name = "District", table = "city", nullable = false, length = 20)
    @Basic(optional = false)
    private String district;

    @Column(name = "Population", table = "city", nullable = false)
    @Basic(optional = false)
    private int population;

    //@JsonManagedReference
    @OneToOne(targetEntity = Country.class)
    @JoinColumn(name = "COUNTRYCAPITAL_CODE")
    protected Country countryCapital;

    //@JsonManagedReference
    @ManyToOne(optional = false, targetEntity = Country.class)
    @JoinColumn(name = "COUNTRYCODE", referencedColumnName = "CODE")
    protected Country country;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public int getPopulation() {
        return this.population;
    }

    public void setPopulation(int population) {
        this.population = population;
    }
    
    public Country getCountryCapital() {
        return this.countryCapital;
    }

    public void setCountryCapital(Country countryCapital) {
        this.countryCapital = countryCapital;
    }
    
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }

}