/**
 * This file was generated by the Jeddict
 */
package data.world;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name = "countrylanguage")
@IdClass(CountryLanguagePK.class)
@JsonIgnoreProperties
public class CountryLanguage {

    @Column(name = "CountryCode", table = "countrylanguage", nullable = false, length = 3)
    @Id
    private String countryCode;

    @Column(name = "Language", table = "countrylanguage", nullable = false, length = 30)
    @Id
    private String language;

    @Column(name = "IsOfficial", table = "countrylanguage", nullable = false, length = 2)
    @Basic(optional = false)
    private String isOfficial;

    @Column(name = "Percentage", table = "countrylanguage", nullable = false)
    @Basic(optional = false)
    private float percentage;

    @ManyToOne(optional = false, targetEntity = Country.class)
    @JoinColumn(name = "COUNTRYCODE", referencedColumnName = "CODE", insertable = false, updatable = false)
    private Country country;

    public String getCountryCode() {
        return this.countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getIsOfficial() {
        return this.isOfficial;
    }

    public void setIsOfficial(String isOfficial) {
        this.isOfficial = isOfficial;
    }

    public float getPercentage() {
        return this.percentage;
    }

    public void setPercentage(float percentage) {
        this.percentage = percentage;
    }

    public Country getCountry() {
        return this.country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

}