/**
 * This file was generated by the Jeddict
 */
package data.world;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

@Entity
@Table(name = "country")
@JsonIgnoreProperties
public class Country {

    @Column(name = "Code", table = "country", nullable = false, length = 3)
    @Id
    private String code;

    @Column(name = "Name", table = "country", nullable = false, length = 52)
    @Basic(optional = false)
    private String name;

    @Column(name = "Continent", table = "country", nullable = false, length = 13)
    @Basic(optional = false)
    private String continent;

    @Column(name = "Region", table = "country", nullable = false, length = 26)
    @Basic(optional = false)
    private String region;

    @Column(name = "SurfaceArea", table = "country", nullable = false)
    @Basic(optional = false)
    private float surfaceArea;

    @Column(name = "IndepYear", table = "country")
    @Basic
    private Short indepYear;

    @Column(name = "Population", table = "country", nullable = false)
    @Basic(optional = false)
    private int population;

    @Column(name = "LifeExpectancy", table = "country", scale = 1, precision = 3)
    @Basic
    private Float lifeExpectancy;

    @Column(name = "GNP", table = "country", scale = 2, precision = 10)
    @Basic
    private Float gnp;

    @Column(name = "GNPOld", table = "country", scale = 2, precision = 10)
    @Basic
    private Float gNPOld;

    @Column(name = "LocalName", table = "country", nullable = false, length = 45)
    @Basic(optional = false)
    private String localName;

    @Column(name = "GovernmentForm", table = "country", nullable = false, length = 45)
    @Basic(optional = false)
    private String governmentForm;

    @Column(name = "HeadOfState", table = "country", length = 60)
    @Basic
    private String headOfState;

    @Column(name = "Capital", table = "country")
    @Basic
    private Integer capital;

    @Column(name = "Code2", table = "country", nullable = false, length = 2)
    @Basic(optional = false)
    private String code2;

    //@JsonBackReference
    @OneToOne(targetEntity = City.class, mappedBy = "countryCapital")
    private City cityCapital;

    @OneToMany(targetEntity = City.class, mappedBy = "country")
    @JsonIgnore
    private List<City> cities;

    @OneToMany(targetEntity = CountryLanguage.class, mappedBy = "country")
    @JsonIgnore
    private List<CountryLanguage> languages;

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getContinent() {
        return this.continent;
    }

    public void setContinent(String continent) {
        this.continent = continent;
    }

    public String getRegion() {
        return this.region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public float getSurfaceArea() {
        return this.surfaceArea;
    }

    public void setSurfaceArea(float surfaceArea) {
        this.surfaceArea = surfaceArea;
    }

    public Short getIndepYear() {
        return this.indepYear;
    }

    public void setIndepYear(Short indepYear) {
        this.indepYear = indepYear;
    }

    public int getPopulation() {
        return this.population;
    }

    public void setPopulation(int population) {
        this.population = population;
    }

    public Float getLifeExpectancy() {
        return this.lifeExpectancy;
    }

    public void setLifeExpectancy(Float lifeExpectancy) {
        this.lifeExpectancy = lifeExpectancy;
    }

    public Float getGnp() {
        return this.gnp;
    }

    public void setGnp(Float gnp) {
        this.gnp = gnp;
    }

    public Float getGNPOld() {
        return this.gNPOld;
    }

    public void setGNPOld(Float gNPOld) {
        this.gNPOld = gNPOld;
    }

    public String getLocalName() {
        return this.localName;
    }

    public void setLocalName(String localName) {
        this.localName = localName;
    }

    public String getGovernmentForm() {
        return this.governmentForm;
    }

    public void setGovernmentForm(String governmentForm) {
        this.governmentForm = governmentForm;
    }

    public String getHeadOfState() {
        return this.headOfState;
    }

    public void setHeadOfState(String headOfState) {
        this.headOfState = headOfState;
    }

    public Integer getCapital() {
        return this.capital;
    }

    public void setCapital(Integer capital) {
        this.capital = capital;
    }

    public String getCode2() {
        return this.code2;
    }

    public void setCode2(String code2) {
        this.code2 = code2;
    }

    public City getCityCapital() {
        return this.cityCapital;
    }

    public void setCityCapital(City cityCapital) {
        this.cityCapital = cityCapital;
    }

    public List<City> getCities() {
        return this.cities;
    }

    public void setCities(List<City> cities) {
        this.cities = cities;
    }

    public List<CountryLanguage> getLanguages() {
        return this.languages;
    }

    public void setLanguages(List<CountryLanguage> languages) {
        this.languages = languages;
    }

}